import { getSiteSettings } from "@/sanity/utils/queries";
import urlFor from "@/lib/imageUrlBuilder";
import { organization } from "@/lib/constants";

export const metadata = {
  title: organization,
  description: `Generated by ${organization}`,
};

export default async function RootLayout({ children }) {
  const siteSettings = await getSiteSettings();
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
